### Sign Up Request
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "email": "user3@mail.com",
    "password": "user3@123@ABC"
}

### Sign In Request
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email": "user3@mail.com",
    "password": "user3@123@ABC"
}

### Find a particular User by ID
GET http://localhost:3000/auth/1

### Get all users filtered by Email
GET http://localhost:3000/auth?email=user@mail.com

### Get all users
GET http://localhost:3000/auth

### Delete a user by ID
DELETE http://localhost:3000/auth/5

### Update a user by ID
PATCH http://localhost:3000/auth/2

{
    "email": "user2new2@mail.com"
}

### Color test
GET http://localhost:3000/auth/colors/red

###
GET http://localhost:3000/auth/colors